---
# cPanel Git Deployment Configuration for Gatherly EMS
# This file automatically deploys your project when you push to the repository

deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home/c2lkis/public_html/
    - export REPOPATH=/home/c2lkis/repositories/Gatherly-EMS_2025

    # Create necessary directories if they don't exist
    - mkdir -p $DEPLOYPATH
    - mkdir -p $DEPLOYPATH/public
    - mkdir -p $DEPLOYPATH/src
    - mkdir -p $DEPLOYPATH/ml
    - mkdir -p $DEPLOYPATH/db
    - mkdir -p $DEPLOYPATH/config

    # Deploy PHP files and directories
    - echo "Deploying PHP files..."
    - /bin/cp -R $REPOPATH/public $DEPLOYPATH
    - /bin/cp -R $REPOPATH/src $DEPLOYPATH
    - /bin/cp -R $REPOPATH/db $DEPLOYPATH

    # Deploy configuration files (IMPORTANT: needed for database connection)
    - echo "Deploying config files..."
    - /bin/cp -R $REPOPATH/config $DEPLOYPATH

    # Deploy .env file if it exists in repository (for initial setup)
    - if [ -f $REPOPATH/.env ]; then /bin/cp $REPOPATH/.env $DEPLOYPATH/.env 2>&1 || true; fi
    - echo "NOTE: If .env is missing, create it manually in $DEPLOYPATH with your database credentials"

    # Deploy other configuration files
    - /bin/cp $REPOPATH/tailwind.config.js $DEPLOYPATH
    - /bin/cp $REPOPATH/package.json $DEPLOYPATH

    # Deploy Python ML system (with debug log file)
    - echo "========================================" > $DEPLOYPATH/deployment-debug.log
    - echo "ML Directory Deployment Debug Log" >> $DEPLOYPATH/deployment-debug.log
    - echo "Deployed on: $(date)" >> $DEPLOYPATH/deployment-debug.log
    - echo "========================================" >> $DEPLOYPATH/deployment-debug.log
    - echo "" >> $DEPLOYPATH/deployment-debug.log
    - echo "Repository path: $REPOPATH" >> $DEPLOYPATH/deployment-debug.log
    - echo "Deployment path: $DEPLOYPATH" >> $DEPLOYPATH/deployment-debug.log
    - echo "" >> $DEPLOYPATH/deployment-debug.log
    - echo "Checking if ml directory exists in repo..." >> $DEPLOYPATH/deployment-debug.log
    - test -d $REPOPATH/ml && echo "✓ ml directory exists in repo" >> $DEPLOYPATH/deployment-debug.log || echo "✗ ml directory NOT FOUND in repo" >> $DEPLOYPATH/deployment-debug.log
    - echo "" >> $DEPLOYPATH/deployment-debug.log
    - echo "Listing ml files in repo:" >> $DEPLOYPATH/deployment-debug.log
    - ls -1 $REPOPATH/ml/ >> $DEPLOYPATH/deployment-debug.log 2>&1 || echo "Failed to list ml files" >> $DEPLOYPATH/deployment-debug.log
    - echo "" >> $DEPLOYPATH/deployment-debug.log
    - echo "Removing old ml directory from deployment if exists..." >> $DEPLOYPATH/deployment-debug.log
    - rm -rf $DEPLOYPATH/ml >> $DEPLOYPATH/deployment-debug.log 2>&1 || true
    - echo "Creating fresh ml directory..." >> $DEPLOYPATH/deployment-debug.log
    - mkdir -p $DEPLOYPATH/ml
    - echo "" >> $DEPLOYPATH/deployment-debug.log
    - echo "Copying ml directory contents..." >> $DEPLOYPATH/deployment-debug.log
    - /bin/cp -v $REPOPATH/ml/* $DEPLOYPATH/ml/ >> $DEPLOYPATH/deployment-debug.log 2>&1 || echo "Copy failed with exit code: $?" >> $DEPLOYPATH/deployment-debug.log
    - echo "" >> $DEPLOYPATH/deployment-debug.log
    - echo "Verifying deployed ml directory..." >> $DEPLOYPATH/deployment-debug.log
    - test -d $DEPLOYPATH/ml && echo "✓ ml directory exists in deployment" >> $DEPLOYPATH/deployment-debug.log || echo "✗ ml directory NOT FOUND in deployment" >> $DEPLOYPATH/deployment-debug.log
    - echo "" >> $DEPLOYPATH/deployment-debug.log
    - echo "Listing deployed ml files:" >> $DEPLOYPATH/deployment-debug.log
    - ls -1 $DEPLOYPATH/ml/ >> $DEPLOYPATH/deployment-debug.log 2>&1 || echo "Failed to list deployed ml files" >> $DEPLOYPATH/deployment-debug.log
    - echo "" >> $DEPLOYPATH/deployment-debug.log
    - echo "File counts:" >> $DEPLOYPATH/deployment-debug.log
    - echo "Total files: $(find $DEPLOYPATH/ml -type f 2>/dev/null | wc -l)" >> $DEPLOYPATH/deployment-debug.log
    - echo "Python files: $(find $DEPLOYPATH/ml -name '*.py' 2>/dev/null | wc -l)" >> $DEPLOYPATH/deployment-debug.log
    - echo "PHP files: $(find $DEPLOYPATH/ml -name '*.php' 2>/dev/null | wc -l)" >> $DEPLOYPATH/deployment-debug.log
    - echo "" >> $DEPLOYPATH/deployment-debug.log
    - echo "Copying root requirements.txt..." >> $DEPLOYPATH/deployment-debug.log
    - /bin/cp -v $REPOPATH/requirements.txt $DEPLOYPATH/requirements.txt >> $DEPLOYPATH/deployment-debug.log 2>&1 || true
    - echo "" >> $DEPLOYPATH/deployment-debug.log
    - echo "========================================" >> $DEPLOYPATH/deployment-debug.log
    - echo "Deployment log complete!" >> $DEPLOYPATH/deployment-debug.log
    - echo "View this file at: http://c2lkis.com/deployment-debug.log" >> $DEPLOYPATH/deployment-debug.log
    - echo "========================================" >> $DEPLOYPATH/deployment-debug.log

    # Install Python dependencies if pip is available
    - echo "Installing Python dependencies..."
    - cd $DEPLOYPATH
    - if command -v pip3 &> /dev/null; then pip3 install --user -r requirements.txt 2>&1 || true; fi

    # Build Tailwind CSS (copy pre-built version as fallback)
    - echo "Deploying Tailwind CSS..."
    - if [ -f $REPOPATH/src/output.css ]; then /bin/cp $REPOPATH/src/output.css $DEPLOYPATH/src/output.css; fi
    - if command -v npx &> /dev/null; then cd $DEPLOYPATH && npx tailwindcss -i ./src/input.css -o ./src/output.css --minify 2>&1 || true; fi

    # Set proper permissions
    - echo "Setting permissions..."
    - chmod -R 755 $DEPLOYPATH/public 2>&1 || true
    - chmod -R 755 $DEPLOYPATH/src 2>&1 || true
    - chmod -R 755 $DEPLOYPATH/ml 2>&1 || true
    - find $DEPLOYPATH -type f -name "*.php" -exec chmod 644 {} \; 2>&1 || true
    - find $DEPLOYPATH -type f -name "*.py" -exec chmod 755 {} \; 2>&1 || true

    # Create .htaccess if it doesn't exist
    - if [ -f $REPOPATH/public/.htaccess ]; then /bin/cp $REPOPATH/public/.htaccess $DEPLOYPATH/public/.htaccess 2>&1 || true; fi

    # Deployment complete
    - echo "Deployment completed successfully!"
    - echo "Deployed on $(date)" >> $DEPLOYPATH/last_deployment.txt
