---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/broscafe/public_html/

    - mkdir -p $DEPLOYPATH
    - mkdir -p $DEPLOYPATH/config
    - mkdir -p $DEPLOYPATH/public
    - mkdir -p $DEPLOYPATH/src
    - mkdir -p $DEPLOYPATH/ml

    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    # - /bin/cp 400.shtml $DEPLOYPATH
    # - /bin/cp 401.shtml $DEPLOYPATH
    # - /bin/cp 403.shtml $DEPLOYPATH
    # - /bin/cp 404.shtml $DEPLOYPATH
    # - /bin/cp 500.shtml $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R ml $DEPLOYPATH
